version: '3'

services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: api
    environment:
    - DB_HOST=db
    - DB_USER=postgres
    - DB_PASSWORD=localpass
    - DB_NAME=team
    networks:
    - dc_net
    ports:
    - 8887:3000
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes:
    - ./:/code

  db:
    container_name: api_db
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=localpass
    - POSTGRES_DB=team
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 5
    logging:
      driver: none
    user: postgres
    networks:
    - dc_net
    ports:
    - 8888:5432
    restart: unless-stopped
    stop_signal: SIGKILL

networks:
  dc_net: {}
